# Generated by Django 2.1.2 on 2018-10-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20181004_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11)),
                ('mail', models.CharField(max_length=320)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='mail',
            field=models.CharField(default='', max_length=320),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
    ]
