# Generated by Django 2.1.2 on 2018-10-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20181021_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publish',
        ),
    ]
