# Generated by Django 2.1.2 on 2018-10-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20181028_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='你好鸭', max_length=20),
        ),
    ]
