# Generated by Django 2.1.2 on 2018-10-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_auto_20181028_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain_num',
            field=models.CharField(default='2016011392', max_length=10),
        ),
    ]
