# Generated by Django 2.1.2 on 2018-10-29 03:00

from django.db import migrations
import myblog.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_employee_choose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='choose',
            field=myblog.fields.ListField(),
        ),
    ]
