# Generated by Django 2.1.2 on 2018-10-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0015_auto_20181030_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
