# Generated by Django 2.1.2 on 2018-10-30 11:58

from django.db import migrations, models
import myblog.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0016_delete_interview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default='国标队', max_length=32)),
                ('date', models.CharField(default='10/30/2018', max_length=32)),
                ('start_time', models.CharField(default='9:25:00 AM', max_length=32)),
                ('end_time', models.CharField(default='11:25:00 AM', max_length=32)),
                ('location', models.CharField(default='蒙民伟楼', max_length=32)),
                ('remarks', models.CharField(default='多喝热水', max_length=600)),
                ('judge_list', myblog.fields.ListField()),
            ],
        ),
    ]
