# Generated by Django 2.1.1 on 2018-11-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0017_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='txted',
            field=models.CharField(default='无', max_length=4000),
        ),
    ]
