# Generated by Django 2.1.1 on 2018-11-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0018_employee_txted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='choose',
        ),
    ]
