# Generated by Django 2.1.1 on 2018-11-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0018_employee_txted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='choose',
            field=models.CharField(default='无', max_length=4000),
        ),
    ]
