# Generated by Django 2.1.1 on 2018-11-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0019_auto_20181105_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='judge_list',
            field=models.CharField(default='无', max_length=4000),
        ),
    ]
