# Generated by Django 2.1.1 on 2018-11-01 12:13

from django.db import migrations
import myblog.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0019_remove_employee_choose'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='choose',
            field=myblog.fields.ListField(default='wu'),
        ),
    ]
