# Generated by Django 2.1.1 on 2018-11-04 16:00

from django.db import migrations
import myblog.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0020_employee_choose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='choose',
            field=myblog.fields.ListField(default=''),
        ),
    ]
