# Generated by Django 2.1.2 on 2018-11-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0020_auto_20181106_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='student_list',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='choose',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='interview',
            name='judge_list',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
