# Generated by Django 2.1.2 on 2018-11-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0021_auto_20181107_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='open_bool',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.AlterField(
            model_name='employee',
            name='choose',
            field=models.CharField(default='无', max_length=4000),
        ),
        migrations.AlterField(
            model_name='interview',
            name='judge_list',
            field=models.CharField(default='无', max_length=4000),
        ),
        migrations.AlterField(
            model_name='interview',
            name='student_list',
            field=models.CharField(default='无', max_length=4000),
        ),
    ]
